server:
  port: 8088
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql:///praveendb
    username: root
  profiles: dev
  
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql:///praveendb
    username: root
  profiles: test
  
---
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: manager
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
  profiles: uat
  
---
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: manager
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
  profiles: prod
  
---
spring:
  profiles:
    active: uat

  
    
    
